// Code generated by "stringer -type=CompressionType"; DO NOT EDIT.

package dsst

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[CompressionTypeNone-0]
	_ = x[CompressionTypeSnappy-1]
	_ = x[CompressionTypeZstd-2]
}

const _CompressionType_name = "CompressionTypeNoneCompressionTypeSnappyCompressionTypeZstd"

var _CompressionType_index = [...]uint8{0, 19, 40, 59}

func (i CompressionType) String() string {
	if i >= CompressionType(len(_CompressionType_index)-1) {
		return "CompressionType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _CompressionType_name[_CompressionType_index[i]:_CompressionType_index[i+1]]
}
