// Code generated by "stringer -type=EntryType"; DO NOT EDIT.

package dsst

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[EntryTypeKeyValue-0]
	_ = x[EntryTypeTombstone-1]
}

const _EntryType_name = "EntryTypeKeyValueEntryTypeTombstone"

var _EntryType_index = [...]uint8{0, 17, 35}

func (i EntryType) String() string {
	if i >= EntryType(len(_EntryType_index)-1) {
		return "EntryType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _EntryType_name[_EntryType_index[i]:_EntryType_index[i+1]]
}
